update

diff --git a/.github/workflows/manual.yml b/.github/workflows/manual.yml
--- a/.github/workflows/manual.yml
+++ b/.github/workflows/manual.yml
@@ -27,15 +27,9 @@ jobs:
         git clone https://github.com/wokwi/wokwi-cli
         cd wokwi-cli
         npm install
-        echo "Before npm link -> which wokwi-cli:"
-        which wokwi-cli || echo "wokwi-cli not found yet"
-        echo "Run npm link"
-        sudo npm link
-        export PATH=$PATH:/usr/local/bin
-        echo "After npm link -> which wokwi-cli:"
-        which wokwi-cli || echo "wokwi-cli not found after npm link"
-        echo "Check npm global packages"
-        npm list -g --depth=0
+        sudo npm install -g .
+        echo "After npm install -g -> which wokwi-cli:"
+        which wokwi-cli || echo "wokwi-cli not found after npm install -g"
 
     - name: Install Python dependencies
       run: |
